module.exports = [
  { line_nm: "1", station_nm: "학동증심사입구" },
  { line_nm: "1", station_nm: "남광주" },
  { line_nm: "1", station_nm: "문화전당" },
  { line_nm: "1", station_nm: "금남로7가" },
  { line_nm: "1", station_nm: "금남로8가" },
  { line_nm: "1", station_nm: "양동시장" },
  { line_nm: "1", station_nm: "돌고개" },
  { line_nm: "1", station_nm: "농성" },
  { line_nm: "1", station_nm: "화정" },
  { line_nm: "1", station_nm: "쌍촌" },
  { line_nm: "1", station_nm: "운천" },
  { line_nm: "1", station_nm: "상무" },
  { line_nm: "1", station_nm: "김대중컨벤션센터" },
  { line_nm: "1", station_nm: "공항" },
  { line_nm: "1", station_nm: "송정공원" },
  { line_nm: "1", station_nm: "광주송정역" },
  { line_nm: "1", station_nm: "도산" },
  { line_nm: "1", station_nm: "평동" },
];
